(module
  (import "weewasm" "obj.new" (func $n (result externref)))
  (import "weewasm" "obj.get" (func $g (param externref externref) (result externref)))
  (import "weewasm" "obj.set" (func $s (param externref externref externref)))
  (import "weewasm" "obj.box_i32" (func $b (param i32) (result externref)))
  (import "weewasm" "i32.unbox" (func $u (param externref) (result i32)))
  (func (export "main") (result i32)
    (local $f externref)
    (local $g externref)
    (local.set $f (call $n))
    (local.set $g (call $n))
    (call $s (local.get $g) (call $b (i32.const 222)) (call $b (i32.const 111)))
    (call $s (local.get $f) (local.get $g) (call $b (i32.const 1234)))
    (call $u (call $g (local.get $f) (call $n)))
  )
)
