(module
  (import "weewasm" "obj.new" (func $n (result externref)))
  (import "weewasm" "obj.get" (func $g (param externref externref) (result externref)))
  (import "weewasm" "obj.set" (func $s (param externref externref externref)))
  (import "weewasm" "obj.box_f64" (func $b (param f64) (result externref)))
  (import "weewasm" "f64.unbox" (func $u (param externref) (result f64)))
  (func (export "main") (param f64) (result f64)
    (local $f externref)
    (local $g externref)
    (local.set $f (call $n))
    (local.set $g (call $n))
    (call $s (local.get $f) (local.get $g) (call $b (local.get 0)))
    (call $u (call $g (local.get $f) (local.get $g)))
  )
)
